// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wallet} from '../models';
import {config} from '../models';
import {backend} from '../models';
import {network} from '../models';

export function ListWallets():Promise<wallet.ListWalletsResponse|Error>;

export function UpdateAppConfig(arg1:config.Config):Promise<Error>;

export function ConsentToTransaction(arg1:backend.ConsentToTransactionRequest):Promise<Error>;

export function GetVersion():Promise<backend.GetVersionResponse>;

export function ListNetworks():Promise<network.ListNetworksResponse|Error>;

export function SaveNetworkConfig(arg1:network.Network):Promise<boolean|Error>;

export function StartConsole(arg1:backend.StartServiceRequest):Promise<boolean|Error>;

export function StartService(arg1:backend.StartServiceRequest):Promise<boolean|Error>;

export function GetAppConfig():Promise<config.Config|Error>;

export function IsAppInitialised():Promise<boolean|Error>;

export function ListConsentRequests():Promise<backend.ListConsentRequestsResponse|Error>;

export function ImportNetwork(arg1:network.ImportNetworkFromSourceRequest):Promise<network.ImportNetworkFromSourceResponse|Error>;

export function SearchForExistingConfiguration():Promise<backend.SearchForExistingConfigurationResponse|Error>;

export function AnnotateKey(arg1:wallet.AnnotateKeyRequest):Promise<Error>;

export function CreateWallet(arg1:wallet.CreateWalletRequest):Promise<wallet.CreateWalletResponse|Error>;

export function GetServiceState():Promise<backend.GetServiceStateResponse>;

export function StopService():Promise<boolean|Error>;

export function ClearSentTransaction(arg1:backend.ClearSentTransactionRequest):Promise<Error>;

export function DescribeKey(arg1:wallet.DescribeKeyRequest):Promise<wallet.DescribeKeyResponse|Error>;

export function GenerateKey(arg1:wallet.GenerateKeyRequest):Promise<wallet.GenerateKeyResponse|Error>;

export function GetConsentRequest(arg1:backend.GetConsentRequestRequest):Promise<backend.ConsentRequest|Error>;

export function GetConsoleState():Promise<backend.GetServiceStateResponse>;

export function SignMessage(arg1:wallet.SignMessageRequest):Promise<wallet.SignMessageResponse|Error>;

export function DeleteWallet(arg1:backend.DeleteWalletRequest):Promise<Error>;

export function GetNetworkConfig(arg1:string):Promise<network.Network|Error>;

export function TaintKey(arg1:wallet.TaintKeyRequest):Promise<Error>;

export function UntaintKey(arg1:wallet.UntaintKeyRequest):Promise<Error>;

export function CheckVersion():Promise<backend.CheckVersionResponse|Error>;

export function ImportWallet(arg1:wallet.ImportWalletRequest):Promise<wallet.ImportWalletResponse|Error>;

export function ListKeys(arg1:wallet.ListKeysRequest):Promise<wallet.ListKeysResponse|Error>;

export function ListSentTransactions():Promise<backend.ListSentTransactionsResponse|Error>;

export function StartTokenDApp(arg1:backend.StartServiceRequest):Promise<boolean|Error>;

export function StopConsole():Promise<boolean|Error>;

export function StopTokenDApp():Promise<boolean|Error>;

export function GetTokenDAppState():Promise<backend.GetServiceStateResponse>;

export function InitialiseApp(arg1:backend.InitialiseAppRequest):Promise<Error>;

export function IsolateKey(arg1:wallet.IsolateKeyRequest):Promise<wallet.IsolateKeyResponse|Error>;
