// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnnotateKey(arg1) {
  return window['go']['backend']['Handler']['AnnotateKey'](arg1);
}

export function CheckVersion() {
  return window['go']['backend']['Handler']['CheckVersion']();
}

export function ClearSentTransaction(arg1) {
  return window['go']['backend']['Handler']['ClearSentTransaction'](arg1);
}

export function ConsentToTransaction(arg1) {
  return window['go']['backend']['Handler']['ConsentToTransaction'](arg1);
}

export function CreateWallet(arg1) {
  return window['go']['backend']['Handler']['CreateWallet'](arg1);
}

export function DeleteWallet(arg1) {
  return window['go']['backend']['Handler']['DeleteWallet'](arg1);
}

export function DescribeKey(arg1) {
  return window['go']['backend']['Handler']['DescribeKey'](arg1);
}

export function GenerateKey(arg1) {
  return window['go']['backend']['Handler']['GenerateKey'](arg1);
}

export function GetAppConfig() {
  return window['go']['backend']['Handler']['GetAppConfig']();
}

export function GetConsentRequest(arg1) {
  return window['go']['backend']['Handler']['GetConsentRequest'](arg1);
}

export function GetNetworkConfig(arg1) {
  return window['go']['backend']['Handler']['GetNetworkConfig'](arg1);
}

export function GetServiceState() {
  return window['go']['backend']['Handler']['GetServiceState']();
}

export function GetVersion() {
  return window['go']['backend']['Handler']['GetVersion']();
}

export function ImportNetwork(arg1) {
  return window['go']['backend']['Handler']['ImportNetwork'](arg1);
}

export function ImportWallet(arg1) {
  return window['go']['backend']['Handler']['ImportWallet'](arg1);
}

export function InitialiseApp(arg1) {
  return window['go']['backend']['Handler']['InitialiseApp'](arg1);
}

export function IsAppInitialised() {
  return window['go']['backend']['Handler']['IsAppInitialised']();
}

export function IsolateKey(arg1) {
  return window['go']['backend']['Handler']['IsolateKey'](arg1);
}

export function ListConsentRequests() {
  return window['go']['backend']['Handler']['ListConsentRequests']();
}

export function ListKeys(arg1) {
  return window['go']['backend']['Handler']['ListKeys'](arg1);
}

export function ListNetworks() {
  return window['go']['backend']['Handler']['ListNetworks']();
}

export function ListSentTransactions() {
  return window['go']['backend']['Handler']['ListSentTransactions']();
}

export function ListWallets() {
  return window['go']['backend']['Handler']['ListWallets']();
}

export function SaveNetworkConfig(arg1) {
  return window['go']['backend']['Handler']['SaveNetworkConfig'](arg1);
}

export function SearchForExistingConfiguration() {
  return window['go']['backend']['Handler']['SearchForExistingConfiguration']();
}

export function SignMessage(arg1) {
  return window['go']['backend']['Handler']['SignMessage'](arg1);
}

export function StartService(arg1) {
  return window['go']['backend']['Handler']['StartService'](arg1);
}

export function StopService() {
  return window['go']['backend']['Handler']['StopService']();
}

export function TaintKey(arg1) {
  return window['go']['backend']['Handler']['TaintKey'](arg1);
}

export function UntaintKey(arg1) {
  return window['go']['backend']['Handler']['UntaintKey'](arg1);
}

export function UpdateAppConfig(arg1) {
  return window['go']['backend']['Handler']['UpdateAppConfig'](arg1);
}
