// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['backend']['Handler']['GetAppConfig']();
}

export function GetCurrentServiceInfo() {
  return window['go']['backend']['Handler']['GetCurrentServiceInfo']();
}

export function GetVersion() {
  return window['go']['backend']['Handler']['GetVersion']();
}

export function InitialiseApp(arg1) {
  return window['go']['backend']['Handler']['InitialiseApp'](arg1);
}

export function IsAppInitialised() {
  return window['go']['backend']['Handler']['IsAppInitialised']();
}

export function RespondToInteraction(arg1) {
  return window['go']['backend']['Handler']['RespondToInteraction'](arg1);
}

export function SearchForExistingConfiguration() {
  return window['go']['backend']['Handler']['SearchForExistingConfiguration']();
}

export function StartService(arg1) {
  return window['go']['backend']['Handler']['StartService'](arg1);
}

export function StopService() {
  return window['go']['backend']['Handler']['StopService']();
}

export function SubmitWalletAPIRequest(arg1) {
  return window['go']['backend']['Handler']['SubmitWalletAPIRequest'](arg1);
}

export function UpdateAppConfig(arg1) {
  return window['go']['backend']['Handler']['UpdateAppConfig'](arg1);
}
