---

name: Add Issues To Project Board

"on":
  issues:
    types: [opened]

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue project board
        env:
          GITHUB_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
          PROJECT_ID: ${{ secrets.FRONT_END_PROJECT_ID }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id'

  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add "desktop-wallet" label
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "desktop-wallet"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
